export const POSTS_LOAD_START = 'POSTS_LOAD_START';
export const POSTS_LOAD_SUCCESS = 'POSTS_LOAD_SUCCESS';
export const POSTS_LOAD_ERROR = 'POSTS_LOAD_ERROR';

export const USERS_LOAD_START = 'USERS_LOAD_START';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_ERROR = 'USERS_LOAD_ERROR';

export const IS_LOGGED = 'IS_LOGGED';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_DISACTIVE_USER = 'SET_DISACTIVE_USER';
